Frontend portal pagination
massenergize/frontend-portal pull request #1123
Opened 2022-10-10 21:26 UTC by abdullai-t

####  Summary / Highlights

#### Details (Give details about what this PR accomplishes, include any screenshots etc)

#### Testing Steps (Provide details on how your changes can be tested)

#### Requirements (place an `x` in each `[ ]`)
* [ ] I've read and understood the [Contributing Guidelines](/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've tested my changes manually.
* [ ] I've added unit tests to my PR.

##### Transparency ([Project board](https://github.com/orgs/massenergize/projects/7/views/2))
* [ ] I've given my PR a meaningful title.
* [ ] I linked this PR to the relevant issue.
* [ ] I moved the linked issue from the "Sprint backlog" to "In progress" when I started this.
* [ ] I moved the linked issue to "QA Verification" now that it is ready to merge.

2022-10-11 05:21 UTC, frimpongopoku requested changes
LGTM

2022-10-11 05:21 UTC, frimpongopoku commented on src/components/Pages/ProfilePage/ProfilePage.js
> +       console.log('===== ToLog USER========', user);
Remove

2022-10-11 05:21 UTC, frimpongopoku commented on src/components/Pages/ProfilePage/ProfilePage.js
> +       console.log('===== ToLog commms ========', communities);
Remove

2022-10-11 05:21 UTC, frimpongopoku commented on src/components/Pages/ProfilePage/ProfilePage.js
> +      console.log('===== ToLog ========', communities);
Remove

2022-10-24 19:23 UTC, Davidjwkinghorn commented
When I go to test this I get a compilation error. 
"""Failed to compile.

./src/components/Utils.js
  Line 319:3:  Expected an assignment or function call and instead saw an expression  no-unused-expressions

Search for the keywords to learn more about each error."""

2023-04-13 08:22 UTC, closed without merging